name: pre-commit

on:
  pull_request:
  push:
    branches: 
      - master
      - dev

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: clang format support
      run: |
        sudo apt install clang-format cppcheck
    - uses: pre-commit/action@v3.0.0
